### PR TITLE
Move all the frontend source code to src

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

Trying to bring some order to the frontend code, one step is to start organizing the source code. First we should introduce the src folder, to avoid mixing code with configurations / envirnoment stuff / docker / tests / etc...

### CODE REVIEW

**Comment by aerrasti** [comment]
Good news! I see that in this PR you are aplying the prettier changes that we didn't do before. thanks!

**Comment by jordisala1991** [comment]
Things not moved (for now):

* typings.d.ts (to me it should be moved, maybe on a next PR)
* next.config.js (it is mandatory to be on root by next.js, so it can't be moved)
* next-env.d.ts (automatically created by next, maybe it can be gitignored)
* i18n.js (I didn't find how to move it, to me it would make sense to move)
* global.d.ts (should be moved)
* public (can't be moved, next forces to be on root)
* locales (might be moved but since weblate needs to be reconfigured I prefer to not do it on this PR)

Thoughts? @eddsaura @aerrasti

**Comment by aerrasti** [comment]
> ## Things that can't be moved by design:
> * next.config.js
> * next-env.d.ts (automatically created by next, maybe it can be gitignored)
> * i18n.js
> * public
> 
> ## Things not moved (for now):
> * typings.d.ts (to me it should be moved, maybe on a next PR)
> * global.d.ts (should be moved)
> * locales (might be moved but since weblate needs to be reconfigured I prefer to not do it on this PR)
> 
> Thoughts? @eddsaura @aerrasti

For the Typescript config, maybe we can create a `configuration` folder like in this project : 
https://github.com/mantinedev/mantine/tree/master/configuration

**Comment by jordisala1991** [comment]
> > ## Things that can't be moved by design:
> > 
> > * next.config.js
> > * next-env.d.ts (automatically created by next, maybe it can be gitignored)
> > * i18n.js
> > * public
> > 
> > ## Things not moved (for now):
> > 
> > * typings.d.ts (to me it should be moved, maybe on a next PR)
> > * global.d.ts (should be moved)
> > * locales (might be moved but since weblate needs to be reconfigured I prefer to not do it on this PR)
> > 
> > Thoughts? @eddsaura @aerrasti
> 
> For the Typescript config, maybe we can create a `configuration` folder like in this project : https://github.com/mantinedev/mantine/tree/master/configuration

For now I have moved them to the `src/types`, let's see how it goes.

**Comment by eddsaura** [comment]
> 

That's exactly what we did in the PR #100  and what we talked how improve the folder structure for typing etc. For me that's a go!

**Review by aerrasti — APPROVED** [review]

**Review by eddsaura — APPROVED** [review]

**Pull request merged**
